# Site settings
title: "G. BERGERET"
email: "support@gbergeret.org"
description: > 
  Gbergeret.org WebSite.
url: "http://www.gbergeret.org"
baseurl: ""

# Build settings
markdown: kramdown

# User variables
repository: "https://github.com/gbergere/gbergere.github.io"
